export type Language = 'pl' | 'en';

export const UI_COPY = {
  pl: {
    language: 'PL',
    turn: 'Tura',
    seed: 'Ziarno',
    mainMenuTitle: 'WAR FOR CROWN',
    mainMenuSubtitle: 'Najpierw wybierz tryb gry.',
    sofaArcade: 'SOFA ARCADE',
    newGame: 'NOWA GRA',
    rules: 'ZASADY',
    load: 'WCZYTAJ',
    loadJson: 'WCZYTAJ JSON',
    loadMissing: 'Brak zapisu w przegladarce.',
    save: 'ZAPISZ',
    saveJson: 'JSON',
    savedLocal: 'Gra zapisana w przegladarce.',
    loadedLocal: 'Wczytano zapis z przegladarki.',
    loadedJson: 'Wczytano zapis z pliku JSON.',
    back: 'WSTECZ',
    chooseMapTitle: 'WYBIERZ MAPE',
    chooseMapInstruction: 'Obejrzyj mape. Jesli pasuje, potwierdz wybor.',
    seedInputInstruction: 'Wpisz seed. Enter zatwierdza, Esc anuluje.',
    invalidSeed: 'Seed musi byc liczba od 1 do 4294967295.',
    regenerateMap: 'INNA MAPA',
    acceptMap: 'TA MAPA',
    setupTitle: 'GRACZE',
    setupInstruction: 'Wpisz imiona, wybierz kolor i herb.',
    name: 'Imie',
    color: 'Kolor',
    crest: 'Herb',
    start: 'DALEJ',
    confirm: 'POTWIERDZ',
    menu: 'MENU',
    mapInfo: 'MAPA',
    terrainLegend: 'TEREN',
    water: 'Woda',
    terrainColumn: 'Teren',
    incomeColumn: 'Dochod',
    defenceColumn: 'Obrona',
    terrainLegendTooltip: 'Dochod: procent bazowego dochodu z wiosek. Obrona: bazowa sila walki obroncy w tabeli C64.',
    rulesTitle: 'ZASADY',
    rulesTooltips: {
      villageCost: 'Koszt dobudowania jednej wioski w wybranej prowincji.',
      interestRate: 'Odsetki doliczane do posiadanej kasy przy miesiecznym dochodzie.',
      startingSoldiers: 'Armia wpisywana do potwierdzonej stolicy gracza. Nie zmienia neutralnych prowincji.',
      startingMoney: 'Kasa kazdego gracza na poczatku partii.',
      homeMaxFort: 'Najwyzszy poziom fortyfikacji, do ktorego mozna rozbudowac stolice.',
      provinceMaxFort: 'Najwyzszy poziom fortyfikacji w zwyklych prowincjach.',
      royalistAttitude: 'Nastawienie neutralnych rodow. Pelne zachowanie AI bedzie dopinane pozniej.',
      royalistGrowth: 'Docelowy przyrost sil neutralnych rodow w pelniejszych zasadach.',
      royalistInvestment: 'Docelowa sklonnosc neutralnych rodow do inwestowania w pelniejszych zasadach.',
      royalistDistribution: 'Sposob rozlozenia neutralnych rodow na starcie pelniejszych zasad.',
      terrainInfluence: 'Okresla, czy teren zmienia dochody, walke, oba elementy albo nic.',
      showComputerBattles: 'Pokazuje wpisy walk, w ktorych oba rody prowadzi komputer.'
    },
    yes: 'TAK',
    no: 'NIE',
    players: 'Gracze',
    alive: 'zywych',
    total: 'razem',
    provinces: 'Prowincje',
    tiles: 'Pola',
    startingSoldiers: 'Wojsko w stolicy',
    startingMoney: 'Startowa kasa',
    incomePerVillage: 'Dochod za wies',
    villageRange: 'Wioski na prowincji',
    villageCost: 'Koszt wioski',
    soldierCost: 'Koszt zolnierza',
    fortCost: 'Koszt fortu',
    fortLevels: 'Fortyfikacje',
    humanPlayers: 'Graczy ludzi',
    aiBarons: 'Baronow AI',
    aiMode: 'Tryb AI',
    aiModeTooltip: 'C64: zgodnosc z oryginalem. Nasze: porownawczy bot roboczy, docelowo z poziomami trudnosci.',
    computer: 'Komputer',
    continentProvinces: 'Prowincje',
    maxVillages: 'Maks. wiosek',
    maxVillagesMode: 'Limit wiosek',
    perProvince: 'Kazda prow.',
    largestProvince: 'Najwieksza',
    royalistAttitude: 'Krolewscy',
    royalistGrowth: 'Przyrost krolewskich',
    royalistInvestment: 'Inwestycje krolewskich',
    royalistDistribution: 'Rozklad krolewskich',
    terrainInfluence: 'Wplyw terenu',
    showComputerBattles: 'Walki AI vs AI',
    homeMaxFort: 'Maks. fort stolicy',
    provinceMaxFort: 'Maks. fort prowincji',
    playerCastle: 'Zamek gracza',
    interestRate: 'Procent',
    houses: 'RODY',
    houseColumn: 'Rod',
    provinceCountColumn: 'Prow.',
    soldierCountColumn: 'Wojsko',
    mapSoldiersShort: 'Z:',
    mapVillagesShort: 'W:',
    province: 'PROWINCJA',
    events: 'ZDARZENIA',
    noEvents: 'Brak zdarzen',
    money: 'KASA',
    land: 'ziemie',
    noProvince: 'Woda nie jest prowincja.',
    chooseNeutral: 'Wybierz neutralna prowincje i potwierdz.',
    pendingHome: 'Wybrana stolica',
    noHomePending: 'Najpierw kliknij neutralna prowincje.',
    occupied: 'Ta prowincja jest juz zajeta.',
    selectOwnProvince: 'Najpierw wybierz swoja prowincje.',
    borderMissing: 'Brak granicy.',
    chooseTarget: 'Wybierz sasiedni cel.',
    chooseAttackSource: 'Wybierz swoje prowincje przy celu.',
    attackAgain: 'Kolejny atak albo koniec fazy.',
    notEnoughMoney: 'Za malo kasy.',
    notEnoughSoldiers: 'Za malo wojska.',
    villageLimit: 'Limit wiosek osiagniety.',
    fortMaxed: 'Fort jest maksymalny.',
    fortAlready: 'Fort juz ulepszony w tej turze.',
    buildStep: 'Budowa jest w kroku BUDOWA.',
    hireStep: 'Najem jest w kroku BUDOWA.',
    attackStep: 'Atak bedzie w kroku ATAK.',
    moveStep: 'Ruch jest w kroku RUCH.',
    chooseMoveTarget: 'Wybierz inna wlasna prowincje.',
    cannotEqualizeMove: 'Nie da sie wyrownac ruchem w tym kierunku.',
    fortStep: 'Fort jest w kroku BUDOWA.',
    clearSelection: 'Nic nie jest wybrane.',
    neutral: 'Neutralna',
    duplicateNames: 'Imiona musza byc rozne.',
    holdsCrown: 'trzyma korone',
    takes: 'zdobywa',
    holds: 'broni sie',
    battle: 'WALKA',
    battleRound: 'RUNDA',
    battleSummaryTitle: 'WYNIK WALKI',
    battleSummaryConfirm: 'ZAMKNIJ',
    winnerLabel: 'Zwyciezca',
    resolutionLabel: 'Wynik',
    lossesLabel: 'Straty',
    survivorsLabel: 'Zostalo',
    resolutionElimination: 'wybicie',
    resolutionAttackerRetreat: 'odwrot atakujacego',
    resolutionDefenderRetreat: 'odwrot obroncy',
    combatPower: 'SILA',
    fightRound: 'WALCZ',
    viewBattle: 'ZOBACZ',
    retreatAttacker: 'ODWROT ATAKU',
    retreatDefender: 'ODWROT OBRONY',
    attacksInBattle: 'atakuje',
    sources: 'zrodla',
    inProvince: 'w',
    villageBuilt: 'wioski',
    hired: 'Najeto',
    moved: 'Przeniesiono',
    soldiers: 'zolnierzy',
    defenders: 'obroncow',
    target: 'CEL',
    need: 'potrzeba',
    win: 'Wygrana',
    lose: 'Przegrana',
    attack: 'ATAK',
    move: 'PRZENIES',
    village: 'WIES',
    fort: 'FORT',
    recruit: 'NAJMIJ',
    all: 'WSZ',
    gameOver: 'KONIEC GRY',
    crownTaken: 'KORONA ZDOBYTA',
    wins: 'WYGRYWA'
  },
  en: {
    language: 'ENG',
    turn: 'Turn',
    seed: 'Seed',
    mainMenuTitle: 'WAR FOR CROWN',
    mainMenuSubtitle: 'Choose how to start.',
    sofaArcade: 'SOFA ARCADE',
    newGame: 'NEW GAME',
    rules: 'RULES',
    load: 'LOAD',
    loadJson: 'LOAD JSON',
    loadMissing: 'No browser save exists.',
    save: 'SAVE',
    saveJson: 'JSON',
    savedLocal: 'Game saved in this browser.',
    loadedLocal: 'Loaded browser save.',
    loadedJson: 'Loaded JSON save file.',
    back: 'BACK',
    chooseMapTitle: 'CHOOSE MAP',
    chooseMapInstruction: 'Inspect the map. Confirm it if it looks good.',
    seedInputInstruction: 'Enter a seed. Enter confirms, Esc cancels.',
    invalidSeed: 'Seed must be a number from 1 to 4294967295.',
    regenerateMap: 'NEW MAP',
    acceptMap: 'USE MAP',
    setupTitle: 'PLAYERS',
    setupInstruction: 'Enter names, choose colors and crests.',
    name: 'Name',
    color: 'Color',
    crest: 'Crest',
    start: 'NEXT',
    confirm: 'CONFIRM',
    menu: 'MENU',
    mapInfo: 'MAP',
    terrainLegend: 'TERRAIN',
    water: 'Water',
    terrainColumn: 'Terrain',
    incomeColumn: 'Income',
    defenceColumn: 'Defence',
    terrainLegendTooltip: 'Income: percent of base village income. Defence: base defender combat power from the C64 table.',
    rulesTitle: 'RULES',
    rulesTooltips: {
      villageCost: 'Cost of building one village in the selected province.',
      interestRate: 'Interest added to saved money during monthly income.',
      startingSoldiers: 'Army placed in a confirmed player home. It does not change neutral provinces.',
      startingMoney: 'Money each player receives at match start.',
      homeMaxFort: 'Highest fortification level available for home provinces.',
      provinceMaxFort: 'Highest fortification level available for regular provinces.',
      royalistAttitude: 'Neutral house attitude. Full AI behavior will be wired later.',
      royalistGrowth: 'Target neutral-house force growth for fuller rules.',
      royalistInvestment: 'Target neutral-house investment tendency for fuller rules.',
      royalistDistribution: 'Starting layout rule for neutral houses in fuller rules.',
      terrainInfluence: 'Controls whether terrain changes income, combat, both, or neither.',
      showComputerBattles: 'Shows battle log entries where both houses are computer-controlled.'
    },
    yes: 'YES',
    no: 'NO',
    players: 'Players',
    alive: 'alive',
    total: 'total',
    provinces: 'Provinces',
    tiles: 'Tiles',
    startingSoldiers: 'Capital soldiers',
    startingMoney: 'Starting money',
    incomePerVillage: 'Income per village',
    villageRange: 'Villages per province',
    villageCost: 'Village cost',
    soldierCost: 'Soldier cost',
    fortCost: 'Fort cost',
    fortLevels: 'Fortifications',
    humanPlayers: 'Human players',
    aiBarons: 'AI barons',
    aiMode: 'AI mode',
    aiModeTooltip: 'C64: original compatibility. Our AI: comparison workbench bot, later with difficulty levels.',
    computer: 'Computer',
    continentProvinces: 'Provinces',
    maxVillages: 'Max villages',
    maxVillagesMode: 'Village limit',
    perProvince: 'Every province',
    largestProvince: 'Largest province',
    royalistAttitude: 'Royalists',
    royalistGrowth: 'Royalist growth',
    royalistInvestment: 'Royalist investment',
    royalistDistribution: 'Royalist layout',
    terrainInfluence: 'Terrain influence',
    showComputerBattles: 'AI vs AI battles',
    homeMaxFort: 'Max home fort',
    provinceMaxFort: 'Max province fort',
    playerCastle: 'Player castle',
    interestRate: 'Interest',
    houses: 'HOUSES',
    houseColumn: 'House',
    provinceCountColumn: 'Prov.',
    soldierCountColumn: 'Army',
    mapSoldiersShort: 'S:',
    mapVillagesShort: 'V:',
    province: 'PROVINCE',
    events: 'EVENTS',
    noEvents: 'No events yet',
    money: 'MONEY',
    land: 'land',
    noProvince: 'Water has no province.',
    chooseNeutral: 'Choose a neutral province and confirm.',
    pendingHome: 'Selected capital',
    noHomePending: 'Click a neutral province first.',
    occupied: 'That province is already taken.',
    selectOwnProvince: 'Select your province first.',
    borderMissing: 'No border.',
    chooseTarget: 'Choose a border target.',
    chooseAttackSource: 'Choose your provinces next to the target.',
    attackAgain: 'Attack again or end the phase.',
    notEnoughMoney: 'Not enough money.',
    notEnoughSoldiers: 'Not enough soldiers.',
    villageLimit: 'Village limit reached.',
    fortMaxed: 'Fort is maxed.',
    fortAlready: 'Fort already upgraded this turn.',
    buildStep: 'Build during BUILD.',
    hireStep: 'Recruit during BUILD.',
    attackStep: 'Attack during ATTACK.',
    moveStep: 'Move during MOVE.',
    chooseMoveTarget: 'Choose another owned province.',
    cannotEqualizeMove: 'Cannot equalize in this direction.',
    fortStep: 'Upgrade forts during BUILD.',
    clearSelection: 'Nothing is selected.',
    neutral: 'Neutral',
    duplicateNames: 'Player names must be unique.',
    holdsCrown: 'holds the crown',
    takes: 'takes',
    holds: 'holds',
    battle: 'BATTLE',
    battleRound: 'ROUND',
    battleSummaryTitle: 'BATTLE RESULT',
    battleSummaryConfirm: 'CLOSE',
    winnerLabel: 'Winner',
    resolutionLabel: 'Result',
    lossesLabel: 'Losses',
    survivorsLabel: 'Survivors',
    resolutionElimination: 'elimination',
    resolutionAttackerRetreat: 'attacker retreat',
    resolutionDefenderRetreat: 'defender retreat',
    combatPower: 'POWER',
    fightRound: 'FIGHT',
    viewBattle: 'VIEW',
    retreatAttacker: 'RETREAT ATTACK',
    retreatDefender: 'RETREAT DEFENCE',
    attacksInBattle: 'attack',
    sources: 'sources',
    inProvince: 'in',
    villageBuilt: 'villages',
    hired: 'Recruited',
    moved: 'Moved',
    soldiers: 'soldiers',
    defenders: 'defenders',
    target: 'TARGET',
    need: 'need',
    win: 'Win',
    lose: 'Lose',
    attack: 'ATTACK',
    move: 'MOVE',
    village: 'VILLAGE',
    fort: 'FORT',
    recruit: 'RECRUIT',
    all: 'ALL',
    gameOver: 'GAME OVER',
    crownTaken: 'CROWN CLAIMED',
    wins: 'WINS'
  }
} as const;
