export const WORLD_WIDTH = 960;
export const WORLD_HEIGHT = 720;

export const TAU = Math.PI * 2;
export const FIXED_TIMESTEP = 1 / 60;

export const TUNNEL_OUTER_RADIUS = 276;
export const TUNNEL_INNER_RADIUS = 76;

export const PLAYER_LIVES = 3;
export const PLAYER_ANGULAR_SPEED = 2.45;
export const PLAYER_INVULNERABILITY = 1.0;
export const PLAYER_SHOOT_COOLDOWN = 0.14;
export const PLAYER_JUMP_DURATION = 0.2;
export const PLAYER_JUMP_COOLDOWN = 0.35;
export const PLAYER_SHIELD_MAX = 100;
export const PLAYER_SHIELD_REGEN_PER_SECOND = 10;
export const PLAYER_SHIELD_REGEN_DELAY = 1.4;
export const PLAYER_COLLISION_INVULNERABILITY = 0.22;
export const PLAYER_DEATH_SEQUENCE_DURATION = 0.85;
export const PLAYER_RESPAWN_ENTRY_DURATION = 0.75;
export const PLAYER_RESPAWN_INVULNERABILITY = 1.1;
export const PLAYER_SPIN_DAMPING_PER_SECOND = 3.1;
export const PLAYER_SPIN_IMPULSE = 1.65;
export const PLAYER_COLLISION_THETA_PUSH = 0.1;

// Active alpha bounds measured from sprites:
// player 24x21, enemy_standard 24x21, enemy_large 40x25.
export const PLAYER_ACTIVE_WIDTH_PX = 24;
export const PLAYER_ACTIVE_HEIGHT_PX = 21;
export const ENEMY_STANDARD_ACTIVE_WIDTH_PX = 24;
export const ENEMY_STANDARD_ACTIVE_HEIGHT_PX = 21;
export const ENEMY_LARGE_ACTIVE_WIDTH_PX = 40;
export const ENEMY_LARGE_ACTIVE_HEIGHT_PX = 25;

export const PLAYER_SPRITE_SCALE = 2.1;
export const ENEMY_SPRITE_SCALE_NEAR = 2.1;
export const ENEMY_SPRITE_SCALE_FAR = 0.14;
export const ENEMY_LARGE_SCALE_MULTIPLIER = 1;

export const HIT_ARC_PER_SCREEN_PIXEL = 0.00105;
export const HIT_DEPTH_PER_SCREEN_PIXEL = 0.00045;
export const HIT_ARC_MIN = 0.006;
export const HIT_DEPTH_MIN = 0.01;
export const PLAYER_BULLET_HIT_ARC_PADDING = 0.004;
export const PLAYER_BULLET_HIT_DEPTH_PADDING = 0.006;
export const ENEMY_BULLET_HIT_ARC_PADDING = 0.005;
export const ENEMY_BULLET_HIT_DEPTH_PADDING = 0.004;

export const BULLET_DEPTH_SPEED = 0.95;
export const BULLET_LIFETIME = 1.2;
export const ENEMY_BULLET_DEPTH_SPEED = 0.7;
export const ENEMY_BULLET_LIFETIME = 1.3;

export const ENEMY_COUNT = 12;
export const ENEMY_LARGE_COUNT = 1;
export const ENEMY_DEPTH_SPEED = 0.11;
export const ENEMY_FORMATION_ROWS = 3;
export const ENEMY_FORMATION_CENTER_THETA = Math.PI / 2;
export const ENEMY_FORMATION_COL_SPACING = 0.22;
export const ENEMY_FORMATION_ROW_DEPTH_START = 0.84;
export const ENEMY_FORMATION_ROW_DEPTH_STEP = 0.13;
export const ENEMY_FORMATION_SWEEP_ARC = 0.6;
export const ENEMY_FORMATION_SWEEP_SPEED = 0.72;
export const ENEMY_LARGE_SWEEP_SPEED = 0.96;
export const ENEMY_LARGE_SWEEP_ARC = 0.9;
export const ENEMY_SHOOT_INTERVAL = 3.6;
export const ENEMY_SHOOT_INTERVAL_BEHIND = 2.1;
export const ENEMY_BEHIND_DESPAWN_DEPTH = -0.72;
export const ENEMY_STANDARD_HP = 1;
export const ENEMY_LARGE_HP = 4;
export const ENEMY_COLLISION_BOUNCE_DEPTH = 0.14;
export const ENEMY_COLLISION_SHIELD_DAMAGE_STANDARD = 30;
export const ENEMY_COLLISION_SHIELD_DAMAGE_LARGE = 44;

export const ASTEROID_COUNT = 5;
export const ASTEROID_BASE_ANGULAR_SPEED = 0.22;
export const ASTEROID_DEPTH_SPEED = 0.14;
export const ASTEROID_LATERAL_SWAY_AMPLITUDE = 0.12;
export const ASTEROID_LATERAL_SWAY_FREQUENCY = 0.58;
export const ASTEROID_LATERAL_FOLLOW_SPEED = 0.86;
export const ASTEROID_DESPAWN_DEPTH = -0.74;
export const ASTEROID_RESPAWN_DEPTH_START = 1.2;
export const ASTEROID_RESPAWN_DEPTH_STEP = 0.1;
export const ASTEROID_HIT_ARC = 0.082;
export const ASTEROID_HIT_DEPTH_WINDOW = 0.075;
export const ASTEROID_COLLISION_BOUNCE_DEPTH = 0.22;
export const ASTEROID_COLLISION_SHIELD_DAMAGE = 34;

export const ENEMY_BULLET_SHIELD_DAMAGE = 22;

export const SCORE_PER_ENEMY = 100;
