import type { KnowledgeRecord, RelayLink, StarSystem } from './types';
import { ENEMY_CAPITAL_ID, PLAYER_CAPITAL_ID, STARTING_TURN } from './constants';

function createSystem(system: StarSystem): StarSystem {
  return system;
}

export const INITIAL_SYSTEMS: ReadonlyArray<StarSystem> = [
  createSystem({
    id: 'sol',
    name: 'SOL',
    x: 0.6,
    y: 1.9,
    owner: 'player',
    population: 6,
    industry: 5,
    defense: 6,
    shipyard: 4,
    stockpile: 6,
    doctrine: 'BALANCED',
    stability: 90,
    garrison: 10,
    launchCooldown: 0
  }),
  createSystem({
    id: 'eos',
    name: 'EOS',
    x: 1.0,
    y: 0.8,
    owner: 'player',
    population: 4,
    industry: 3,
    defense: 3,
    shipyard: 2,
    stockpile: 3,
    doctrine: 'MILITARY',
    stability: 82,
    garrison: 6,
    launchCooldown: 0
  }),
  createSystem({
    id: 'tau',
    name: 'TAU CETI',
    x: 1.4,
    y: 2.8,
    owner: 'player',
    population: 4,
    industry: 3,
    defense: 2,
    shipyard: 2,
    stockpile: 2,
    doctrine: 'EXPAND',
    stability: 78,
    garrison: 7,
    launchCooldown: 0
  }),
  createSystem({
    id: 'haven',
    name: 'HAVEN',
    x: 1.8,
    y: 1.8,
    owner: 'player',
    population: 5,
    industry: 4,
    defense: 4,
    shipyard: 3,
    stockpile: 4,
    doctrine: 'BALANCED',
    stability: 85,
    garrison: 7,
    launchCooldown: 0
  }),
  createSystem({
    id: 'mir',
    name: 'MIR',
    x: 0.9,
    y: 3.3,
    owner: 'player',
    population: 3,
    industry: 2,
    defense: 2,
    shipyard: 1,
    stockpile: 1,
    doctrine: 'SURVIVAL',
    stability: 74,
    garrison: 5,
    launchCooldown: 0
  }),
  createSystem({
    id: 'kepler',
    name: 'KEPLER GATE',
    x: 2.5,
    y: 1.3,
    owner: 'neutral',
    population: 3,
    industry: 2,
    defense: 2,
    shipyard: 1,
    stockpile: 0,
    doctrine: 'SURVIVAL',
    stability: 68,
    garrison: 3,
    launchCooldown: 0
  }),
  createSystem({
    id: 'umber',
    name: 'UMBER',
    x: 2.7,
    y: 2.7,
    owner: 'neutral',
    population: 3,
    industry: 2,
    defense: 2,
    shipyard: 1,
    stockpile: 0,
    doctrine: 'SURVIVAL',
    stability: 63,
    garrison: 3,
    launchCooldown: 0
  }),
  createSystem({
    id: 'aegis',
    name: 'AEGIS',
    x: 3.2,
    y: 2.1,
    owner: 'neutral',
    population: 4,
    industry: 3,
    defense: 3,
    shipyard: 1,
    stockpile: 0,
    doctrine: 'SURVIVAL',
    stability: 70,
    garrison: 4,
    launchCooldown: 0
  }),
  createSystem({
    id: 'kharon',
    name: 'KHARON',
    x: 3.8,
    y: 0.8,
    owner: 'enemy',
    population: 4,
    industry: 3,
    defense: 3,
    shipyard: 2,
    stockpile: 3,
    doctrine: 'EXPAND',
    stability: 80,
    garrison: 6,
    launchCooldown: 0
  }),
  createSystem({
    id: 'nysa',
    name: 'NYSA',
    x: 4.1,
    y: 1.9,
    owner: 'enemy',
    population: 5,
    industry: 4,
    defense: 4,
    shipyard: 3,
    stockpile: 4,
    doctrine: 'BALANCED',
    stability: 84,
    garrison: 7,
    launchCooldown: 0
  }),
  createSystem({
    id: 'helion',
    name: 'HELION',
    x: 4.4,
    y: 3.1,
    owner: 'enemy',
    population: 4,
    industry: 3,
    defense: 3,
    shipyard: 2,
    stockpile: 3,
    doctrine: 'EXPAND',
    stability: 79,
    garrison: 6,
    launchCooldown: 0
  }),
  createSystem({
    id: 'vanta',
    name: 'VANTA',
    x: 5.0,
    y: 2.3,
    owner: 'enemy',
    population: 6,
    industry: 5,
    defense: 6,
    shipyard: 4,
    stockpile: 6,
    doctrine: 'BALANCED',
    stability: 88,
    garrison: 10,
    launchCooldown: 0
  }),
  createSystem({
    id: 'rook',
    name: 'ROOK',
    x: 5.1,
    y: 1.1,
    owner: 'enemy',
    population: 4,
    industry: 3,
    defense: 3,
    shipyard: 2,
    stockpile: 2,
    doctrine: 'MILITARY',
    stability: 77,
    garrison: 6,
    launchCooldown: 0
  })
];

export const INITIAL_RELAY_LINKS: ReadonlyArray<RelayLink> = [
  { a: 'sol', b: 'haven', owner: 'player' },
  { a: 'haven', b: 'tau', owner: 'player' },
  { a: 'nysa', b: ENEMY_CAPITAL_ID, owner: 'enemy' },
  { a: 'nysa', b: 'kharon', owner: 'enemy' }
];

export const INITIAL_KNOWLEDGE: ReadonlyArray<KnowledgeRecord> = INITIAL_SYSTEMS.map((system) => ({
  systemId: system.id,
  lastKnownOwner: system.owner,
  lastKnownPopulation: system.population,
  lastKnownIndustry: system.industry,
  lastKnownDefense: system.defense,
  lastKnownGarrison: system.garrison,
  lastKnownDoctrine: system.doctrine,
  reportOriginTurn: STARTING_TURN,
  reportArrivalTurn: STARTING_TURN,
  sourceChannel: system.id === PLAYER_CAPITAL_ID ? 'radio' : 'courier'
}));
